// <auto-generated />
using System;
using FitTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222195803_AddHydrationTracking")]
    partial class AddHydrationTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FitTrack.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyCalorieTarget")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyCarbsTarget")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyFatTarget")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyProteinTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitTrack.Models.FoodLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodLibraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 165m,
                            CarbsPer100g = 0m,
                            Category = "Protéine",
                            FatPer100g = 3.6m,
                            IsCustom = false,
                            Name = "Poulet (Poitrine)",
                            ProteinPer100g = 31m
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 111m,
                            CarbsPer100g = 23m,
                            Category = "Céréales",
                            FatPer100g = 0.9m,
                            IsCustom = false,
                            Name = "Riz Brun",
                            ProteinPer100g = 2.6m
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 155m,
                            CarbsPer100g = 1.1m,
                            Category = "Protéine",
                            FatPer100g = 11m,
                            IsCustom = false,
                            Name = "Œufs",
                            ProteinPer100g = 13m
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 400m,
                            CarbsPer100g = 8m,
                            Category = "Supplément",
                            FatPer100g = 5m,
                            IsCustom = false,
                            Name = "Whey Protéine",
                            ProteinPer100g = 80m
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 208m,
                            CarbsPer100g = 0m,
                            Category = "Protéine",
                            FatPer100g = 13m,
                            IsCustom = false,
                            Name = "Saumon",
                            ProteinPer100g = 20m
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 86m,
                            CarbsPer100g = 20m,
                            Category = "Légumes",
                            FatPer100g = 0.1m,
                            IsCustom = false,
                            Name = "Patate Douce",
                            ProteinPer100g = 1.6m
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 120m,
                            CarbsPer100g = 21m,
                            Category = "Céréales",
                            FatPer100g = 1.9m,
                            IsCustom = false,
                            Name = "Quinoa",
                            ProteinPer100g = 4.4m
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 250m,
                            CarbsPer100g = 0m,
                            Category = "Protéine",
                            FatPer100g = 15m,
                            IsCustom = false,
                            Name = "Bœuf Haché Maigre",
                            ProteinPer100g = 26m
                        },
                        new
                        {
                            Id = 9,
                            CaloriesPer100g = 160m,
                            CarbsPer100g = 9m,
                            Category = "Fruits",
                            FatPer100g = 15m,
                            IsCustom = false,
                            Name = "Avocat",
                            ProteinPer100g = 2m
                        },
                        new
                        {
                            Id = 10,
                            CaloriesPer100g = 579m,
                            CarbsPer100g = 22m,
                            Category = "Noix",
                            FatPer100g = 50m,
                            IsCustom = false,
                            Name = "Amandes",
                            ProteinPer100g = 21m
                        },
                        new
                        {
                            Id = 11,
                            CaloriesPer100g = 112m,
                            CarbsPer100g = 23m,
                            Category = "Céréales",
                            FatPer100g = 0.2m,
                            IsCustom = false,
                            Name = "Couscous",
                            ProteinPer100g = 3.8m
                        },
                        new
                        {
                            Id = 12,
                            CaloriesPer100g = 116m,
                            CarbsPer100g = 20m,
                            Category = "Légumineuses",
                            FatPer100g = 0.4m,
                            IsCustom = false,
                            Name = "Lentilles",
                            ProteinPer100g = 9m
                        },
                        new
                        {
                            Id = 13,
                            CaloriesPer100g = 59m,
                            CarbsPer100g = 3.6m,
                            Category = "Produits Laitiers",
                            FatPer100g = 0.4m,
                            IsCustom = false,
                            Name = "Yaourt Grec",
                            ProteinPer100g = 10m
                        },
                        new
                        {
                            Id = 14,
                            CaloriesPer100g = 89m,
                            CarbsPer100g = 23m,
                            Category = "Fruits",
                            FatPer100g = 0.3m,
                            IsCustom = false,
                            Name = "Banane",
                            ProteinPer100g = 1.1m
                        },
                        new
                        {
                            Id = 15,
                            CaloriesPer100g = 34m,
                            CarbsPer100g = 7m,
                            Category = "Légumes",
                            FatPer100g = 0.4m,
                            IsCustom = false,
                            Name = "Brocoli",
                            ProteinPer100g = 2.8m
                        },
                        new
                        {
                            Id = 16,
                            CaloriesPer100g = 116m,
                            CarbsPer100g = 0m,
                            Category = "Protéine",
                            FatPer100g = 0.8m,
                            IsCustom = false,
                            Name = "Thon en Conserve",
                            ProteinPer100g = 26m
                        },
                        new
                        {
                            Id = 17,
                            CaloriesPer100g = 884m,
                            CarbsPer100g = 0m,
                            Category = "Graisses",
                            FatPer100g = 100m,
                            IsCustom = false,
                            Name = "Huile d'Olive",
                            ProteinPer100g = 0m
                        },
                        new
                        {
                            Id = 18,
                            CaloriesPer100g = 23m,
                            CarbsPer100g = 3.6m,
                            Category = "Légumes",
                            FatPer100g = 0.4m,
                            IsCustom = false,
                            Name = "Épinards",
                            ProteinPer100g = 2.9m
                        },
                        new
                        {
                            Id = 19,
                            CaloriesPer100g = 247m,
                            CarbsPer100g = 41m,
                            Category = "Céréales",
                            FatPer100g = 3.4m,
                            IsCustom = false,
                            Name = "Pain Complet",
                            ProteinPer100g = 13m
                        },
                        new
                        {
                            Id = 20,
                            CaloriesPer100g = 277m,
                            CarbsPer100g = 75m,
                            Category = "Fruits",
                            FatPer100g = 0.2m,
                            IsCustom = false,
                            Name = "Dattes Medjool",
                            ProteinPer100g = 1.8m
                        });
                });

            modelBuilder.Entity("FitTrack.Models.HydrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyGoalMl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MillilitersConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HydrationLogs");
                });

            modelBuilder.Entity("FitTrack.Models.MealLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Calories")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fat")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Protein")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightInGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("MealLogs");
                });

            modelBuilder.Entity("FitTrack.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MuscleMass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("FitTrack.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AchievedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoalValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitTrack.Models.MealLog", b =>
                {
                    b.HasOne("FitTrack.Models.FoodLibrary", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTrack.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTrack.Models.Measure", b =>
                {
                    b.HasOne("FitTrack.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitTrack.Models.Objective", b =>
                {
                    b.HasOne("FitTrack.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FitTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FitTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FitTrack.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
